environment:
  # The.NET Core CLI tries to add the default locations to the PATH environmentvariable on its first usage. Set to true to skip caching
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Specifies whether data about the.NET Coretools usageis collected and sent to Microsoft. Set to true to opt-out of thetelemetry feature
  DOTNET_CLI_TELEMETRY_OPTOUT: true
image: Visual Studio 2019
build: off
deploy: off
skip_tags: true
platform: Any CPU
configuration: Release
build_script:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:ghtoken):x-oauth-basic@github.com`n"
  - git config --global user.email "mynkow@gmail.com"
  - git config --global user.name "mynkow"
  - build.cmd %nuget_key%
